[package]
name = "groth16-verifier-example"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3"
hex = "0.4"
methods = { path = "methods" }
bonsai-groth16 = { path = "../../bonsai/groth16" }
risc0-zkvm = { path = "../../risc0/zkvm" }
serde_json = "1.0"

# Always optimize; building and running the guest takes much longer without optimization.
[profile.dev]
opt-level = 3

[profile.dev.build-override]
opt-level = 3

[profile.release]
debug = 1
lto = true

[profile.release.build-override]
opt-level = 3
