[package]
name = "groth16-verifier-example"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
bincode = "1.3"
bonsai-sdk = { path = "../../bonsai/sdk" }
bytemuck = "1.14"
byteorder = "1.4"
hello-world-methods = { path = "../hello-world/methods" }
hex = "0.4"
risc0-zkvm = { path = "../../risc0/zkvm" }
serde_json = "1.0"

# Always optimize; building and running the guest takes much longer without optimization.
[profile.dev]
opt-level = 3

[profile.dev.build-override]
opt-level = 3

[profile.release]
debug = 1
lto = true

[profile.release.build-override]
opt-level = 3
